name: My first workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List and Read file
          run: |
            echo "Myfirst Github Actions Job"
            ls -ltra
            cat README.md
        
        - name: Generate ACSII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

        # - name: List files
        #   run: ls
          
        # - name: Read file
        #   run: cat README.md